name: Run Tests

on: [push]

jobs:
    php-tests:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                php: [7.4, 8.0, 8.1]
                dependency-version: [lowest, highest]
                exclude:
                    - php: 8.1
                      dependency-version: lowest

        name: PHP ${{ matrix.php }} - ${{ matrix.dependency-version }} on ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3.0.2

            - name: Setup PHP
              uses: shivammathur/setup-php@2.19.0
              with:
                  php-version: ${{ matrix.php }}
                  extensions: mbstring, fileinfo
                  coverage: none

            - name: Install dependencies
              uses: ramsey/composer-install@v1
              with:
                  dependency-versions: ${{ matrix.dependency-version }}
                  composer-options: "--no-suggest --prefer-dist"

            - name: Execute tests
              run: vendor/bin/phpunit
